FROM era-fee-withdrawer-dcap:latest

WORKDIR /app

COPY enclave-key.pem /tmp/

# The final touch for a reproducible docker file
RUN touch -r /nix/store * /etc/sgx_default_qcnl.conf

RUN set -eux; \
    export HOME=/app; \
    gramine-manifest \
      -Darch_libdir=/lib/x86_64-linux-gnu \
      -Dentrypoint=$(readlink /bin/era-fee-withdrawer) \
      -Dexecdir=/bin \
      -Dlog_level=error \
      era-fee-withdrawer.manifest.toml era-fee-withdrawer.manifest; \
    gramine-sgx-sign --manifest era-fee-withdrawer.manifest --output era-fee-withdrawer.manifest.sgx --key /tmp/enclave-key.pem; \
    rm /tmp/enclave-key.pem

# Uncomment, if a signed sigstruct exists
# COPY era-fee-withdrawer-dcap.sig .
# RUN mv era-fee-withdrawer-dcap.sig era-fee-withdrawer.sig
RUN touch -r /nix/store era-fee-withdrawer.sig

ENTRYPOINT ["/bin/sh", "-c"]
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
ENV UV_USE_IO_URING=0

#CMD [ "echo era-fee-withdrawer in simulation mode starting ; exec gramine-direct era-fee-withdrawer" ]
CMD [ "echo era-fee-withdrawer in SGX mode starting ; restart-aesmd ; exec gramine-sgx era-fee-withdrawer" ]
