FROM node:14
WORKDIR /usr/src/fee-withdrawer-v2

COPY . .
RUN yarn install

# required env
# ENV MISC_FEE_ACCOUNT_PRIVATE_KEY
# ENV OPERATOR_ADDRESS
# ENV WITHDRAWAL_FINALIZER_ETH_ADDRESS
# ENV MISC_RESERVE_FEE_ACCUMULATOR_ADDRESS
# ENV L1_RPC_ADDRESS
# ENV ZKSYNC_WEB3_API_URL
# ENV MISC_MAX_LIQUIDATION_FEE_PERCENT
# ENV ZKSYNC_WEB3_API_URL
# ENV LOWER_BOUND_OPERATOR_THRESHOLD
# ENV UPPER_BOUND_OPERATOR_THRESHOLD
# ENV LOWER_BOUND_WITHDRAWER_THRESHOLD
# ENV UPPER_BOUND_WITHDRAWER_THRESHOLD
# ENV LOWER_BOUND_PAYMASTER_THRESHOLD
# ENV UPPER_BOUND_PAYMASTER_THRESHOLD
# optional env
# ENV WATCHDOG_ADDRESS
# ENV LOWER_BOUND_WATCHDOG_THRESHOLD
# ENV UPPER_BOUND_WATCHDOG_THRESHOLD
# ENV L1_ETH_TRANSFER_THRESHOLD
# ENV L2_ETH_TRANSFER_THRESHOLD
# ENV CONTRACTS_L2_TESTNET_PAYMASTER_ADDR
CMD ["yarn", "start"]
