name: CI

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn

      - name: running tests
        run: yarn test

      - name: test Docker image build
        uses: docker/build-push-action@v2.7.0
        with:
          push: false
          file: Dockerfile
          no-cache: true
